package com.model;

// Generated 24 avr. 2014 01:05:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BonDeLivraison generated by hbm2java
 */
@Entity
@Table(name = "BonDeLivraison", catalog = "BD_PCD")
public class BonDeLivraison implements java.io.Serializable {

	private Integer refBonDeLivraison;
	private byte[] bonLivraison;
	private Set<Livraison> livraisons = new HashSet<Livraison>(0);

	public BonDeLivraison() {
	}

	public BonDeLivraison(byte[] bonLivraison, Set<Livraison> livraisons) {
		this.bonLivraison = bonLivraison;
		this.livraisons = livraisons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RefBonDeLivraison", unique = true, nullable = false)
	public Integer getRefBonDeLivraison() {
		return this.refBonDeLivraison;
	}

	public void setRefBonDeLivraison(Integer refBonDeLivraison) {
		this.refBonDeLivraison = refBonDeLivraison;
	}

	@Column(name = "BonLivraison")
	public byte[] getBonLivraison() {
		return this.bonLivraison;
	}

	public void setBonLivraison(byte[] bonLivraison) {
		this.bonLivraison = bonLivraison;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bonDeLivraison")
	public Set<Livraison> getLivraisons() {
		return this.livraisons;
	}

	public void setLivraisons(Set<Livraison> livraisons) {
		this.livraisons = livraisons;
	}

}
