package com.model;

// Generated 24 avr. 2014 01:05:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BonDeCommande generated by hbm2java
 */
@Entity
@Table(name = "BonDeCommande", catalog = "BD_PCD")
public class BonDeCommande implements java.io.Serializable {

	private Integer refBonDeCommande;
	private byte[] bonCommande;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public BonDeCommande() {
	}

	public BonDeCommande(byte[] bonCommande, Set<Commande> commandes) {
		this.bonCommande = bonCommande;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "RefBonDeCommande", unique = true, nullable = false)
	public Integer getRefBonDeCommande() {
		return this.refBonDeCommande;
	}

	public void setRefBonDeCommande(Integer refBonDeCommande) {
		this.refBonDeCommande = refBonDeCommande;
	}

	@Column(name = "BonCommande")
	public byte[] getBonCommande() {
		return this.bonCommande;
	}

	public void setBonCommande(byte[] bonCommande) {
		this.bonCommande = bonCommande;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bonDeCommande")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
