package com.model;

// Generated 24 avr. 2014 01:05:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "Client", catalog = "BD_PCD")
public class Client implements java.io.Serializable {

	private Integer idClient;
	private String nom;
	private String prénom;
	private String numéroTéléphone;
	private String email;
	private String adresse;
	private String ville;
	private String login;
	private String passWord;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Client() {
	}

	public Client(String nom, String prénom, String numéroTéléphone,
			String email, String adresse, String ville, String login,
			String passWord, Set<Commande> commandes) {
		this.nom = nom;
		this.prénom = prénom;
		this.numéroTéléphone = numéroTéléphone;
		this.email = email;
		this.adresse = adresse;
		this.ville = ville;
		this.login = login;
		this.passWord = passWord;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idClient", unique = true, nullable = false)
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "Nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "Prénom", length = 45)
	public String getPrénom() {
		return this.prénom;
	}

	public void setPrénom(String prénom) {
		this.prénom = prénom;
	}

	@Column(name = "NuméroTéléphone", length = 16777215)
	public String getNuméroTéléphone() {
		return this.numéroTéléphone;
	}

	public void setNuméroTéléphone(String numéroTéléphone) {
		this.numéroTéléphone = numéroTéléphone;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Adresse")
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "Ville", length = 45)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "Login", length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "passWord", length = 16777215)
	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
