package com.model;

// Generated 24 avr. 2014 01:05:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "Commande", catalog = "BD_PCD")
public class Commande implements java.io.Serializable {

	private CommandeId id;
	private BonDeCommande bonDeCommande;
	private Client client;
	private Produit produit;
	private String quantité;
	private Date date;

	public Commande() {
	}

	public Commande(CommandeId id, Client client, Produit produit) {
		this.id = id;
		this.client = client;
		this.produit = produit;
	}

	public Commande(CommandeId id, BonDeCommande bonDeCommande, Client client,
			Produit produit, String quantité, Date date) {
		this.id = id;
		this.bonDeCommande = bonDeCommande;
		this.client = client;
		this.produit = produit;
		this.quantité = quantité;
		this.date = date;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "clientIdClient", column = @Column(name = "Client_idClient", nullable = false)),
			@AttributeOverride(name = "produitIdProduit", column = @Column(name = "Produit_idProduit", nullable = false)) })
	public CommandeId getId() {
		return this.id;
	}

	public void setId(CommandeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RefBonDeCommande")
	public BonDeCommande getBonDeCommande() {
		return this.bonDeCommande;
	}

	public void setBonDeCommande(BonDeCommande bonDeCommande) {
		this.bonDeCommande = bonDeCommande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Client_idClient", nullable = false, insertable = false, updatable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Produit_idProduit", nullable = false, insertable = false, updatable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "Quantité", length = 16777215)
	public String getQuantité() {
		return this.quantité;
	}

	public void setQuantité(String quantité) {
		this.quantité = quantité;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
