package com.model;

// Generated 24 avr. 2014 01:05:02 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommandeId generated by hbm2java
 */
@Embeddable
public class CommandeId implements java.io.Serializable {

	private int clientIdClient;
	private int produitIdProduit;

	public CommandeId() {
	}

	public CommandeId(int clientIdClient, int produitIdProduit) {
		this.clientIdClient = clientIdClient;
		this.produitIdProduit = produitIdProduit;
	}

	@Column(name = "Client_idClient", nullable = false)
	public int getClientIdClient() {
		return this.clientIdClient;
	}

	public void setClientIdClient(int clientIdClient) {
		this.clientIdClient = clientIdClient;
	}

	@Column(name = "Produit_idProduit", nullable = false)
	public int getProduitIdProduit() {
		return this.produitIdProduit;
	}

	public void setProduitIdProduit(int produitIdProduit) {
		this.produitIdProduit = produitIdProduit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommandeId))
			return false;
		CommandeId castOther = (CommandeId) other;

		return (this.getClientIdClient() == castOther.getClientIdClient())
				&& (this.getProduitIdProduit() == castOther
						.getProduitIdProduit());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClientIdClient();
		result = 37 * result + this.getProduitIdProduit();
		return result;
	}

}
