package com.model;

// Generated 24 avr. 2014 01:05:02 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LivraisonId generated by hbm2java
 */
@Embeddable
public class LivraisonId implements java.io.Serializable {

	private int produitIdProduit;
	private int fournisseurIdFournisseur;

	public LivraisonId() {
	}

	public LivraisonId(int produitIdProduit, int fournisseurIdFournisseur) {
		this.produitIdProduit = produitIdProduit;
		this.fournisseurIdFournisseur = fournisseurIdFournisseur;
	}

	@Column(name = "Produit_idProduit", nullable = false)
	public int getProduitIdProduit() {
		return this.produitIdProduit;
	}

	public void setProduitIdProduit(int produitIdProduit) {
		this.produitIdProduit = produitIdProduit;
	}

	@Column(name = "Fournisseur_idFournisseur", nullable = false)
	public int getFournisseurIdFournisseur() {
		return this.fournisseurIdFournisseur;
	}

	public void setFournisseurIdFournisseur(int fournisseurIdFournisseur) {
		this.fournisseurIdFournisseur = fournisseurIdFournisseur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LivraisonId))
			return false;
		LivraisonId castOther = (LivraisonId) other;

		return (this.getProduitIdProduit() == castOther.getProduitIdProduit())
				&& (this.getFournisseurIdFournisseur() == castOther
						.getFournisseurIdFournisseur());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProduitIdProduit();
		result = 37 * result + this.getFournisseurIdFournisseur();
		return result;
	}

}
